adds assignNonEnumerable
canjs/can-util pull request #117
Opened 2016-10-03 16:40 UTC by justinbmeyer

for #101

Uses Object.defineProperty to make the added properties non enumerable but still writable.

2016-11-02 19:16 UTC, matthewp requested changes

2016-11-02 19:16 UTC, matthewp commented on js/assign-non-enumerable/assign-non-enumerable.js
> +module.exports = function (d, s) {
You have two module.exports, pretty sure the first is a mistake.

2017-04-27 02:03 UTC, matthewp commented
@justinbmeyer do you plan on updating this PR?

2017-05-11 17:00 UTC, matthewp commented on js/assign-non-enumerable/assign-non-enumerable.js
> +			value: s[prop]
Should it be configurable as well or was that omitted on purpose?

2017-05-11 17:03 UTC, chiefsmurph commented on js/assign-non-enumerable/assign-non-enumerable.js
> +			value: s[prop]
I was unsure about that.  If that is the intention, then it would make sense to utilize `can-util/js/set-not-enumerable/set-not-enumerable`

2017-05-11 17:17 UTC, chiefsmurph commented on js/assign-non-enumerable/assign-non-enumerable.js
> +			value: s[prop]
It does seem that the safe choice would be to leave configurable false so that the prop could still be deleted.

2017-05-11 17:35 UTC, matthewp commented on js/assign-non-enumerable/assign-non-enumerable.js
> +			value: s[prop]
configurable false means the prop isn't deleted, right?  if this is meant to be like Object.assign but non-enumerable it should be configurable true:

<img width="1248" alt="screen shot 2017-05-11 at 1 35 55 pm" src="https://cloud.githubusercontent.com/assets/361671/25963271/b8f3f7d4-364e-11e7-829e-f345d5b6a32c.png">

2017-05-11 18:05 UTC, chiefsmurph commented on js/assign-non-enumerable/assign-non-enumerable.js
> +			value: s[prop]
oh you are right good point I will push a commit now

2017-05-22 21:00 UTC, matthewp approved these changes

2017-05-24 07:54 UTC, merged