allow identity option for diff #174
canjs/can-util pull request #175
Opened 2016-12-28 21:56 UTC by ilyavf

2016-12-28 22:18 UTC, matthewp commented
👍

2016-12-29 20:11 UTC, ilyavf commented
I think this is ready for a review.

2016-12-29 22:05 UTC, justinbmeyer requested changes

2016-12-29 22:05 UTC, justinbmeyer commented on js/diff/diff.js
> + * @param  {function} identity an optional identity function for comparing elements
```
@typdef {function(*,*)} can-util/diff/diff/typedefs.identity identify(a, b)

@param {*} a This is something.
```


```
@param  {can-util/diff/diff/typedefs.identity} identity(a, b)
  @option {*} a
```

2016-12-29 22:05 UTC, justinbmeyer commented on js/diff/diff.js
> +	identity = identity || function(a,b){ return a === b; };
don't re-create the identity function every time.

2017-01-03 17:48 UTC, ilyavf commented on js/diff/diff.js
> +	identity = identity || function(a,b){ return a === b; };
Done.

2017-01-03 17:49 UTC, ilyavf commented on js/diff/diff.js
> + * @param  {function} identity an optional identity function for comparing elements
added a TODO for now.

2017-01-03 21:07 UTC, justinbmeyer approved these changes

2017-01-03 21:07 UTC, merged