added doc for can.each with an object
canjs/can-util pull request #211
Opened 2017-03-21 10:54 UTC by sarathnair

For  #208

Added documentation for can.each on Object

2017-03-21 23:00 UTC, chasenlehara requested changes

2017-03-21 23:00 UTC, chasenlehara commented on js/each/each.md
> +  @return {collection}  the orignal collection
“orignal” => “original”

2017-03-21 23:00 UTC, chasenlehara commented on js/each/each.md
> +  @return {collection}  the orignal collection
I wonder if we should either update the code to use `collection` instead of `elements`, or leave the argument documented as `elements`.

2017-03-22 06:04 UTC, sarathnair commented on js/each/each.md
> +  @return {collection}  the orignal collection
What's your opinion on adding two signatures to it like jQuery does? http://api.jquery.com/jquery.each/
I will generate a PR for that

2017-03-22 06:30 UTC, sarathnair commented on js/each/each.md
> +  @return {collection}  the orignal collection
I have made the mentioned changes and added more info to the docs

2017-03-22 14:58 UTC, chasenlehara approved these changes

2017-03-22 15:32 UTC, phillipskevin approved these changes
Looks good to me. Thanks @sarathnair!

2017-03-23 05:37 UTC, merged