Adding delegated enter/leave events derived from over/move events.
canjs/can-util pull request #253
Opened 2017-04-27 18:41 UTC by nlundquist

Fixes #239.

2017-04-27 18:43 UTC, nlundquist commented on dom/events/delegate/derive-enter-leave.js
> +    this._derivedHandlers = this._derivedHandlers || {};
Should I keep the reference to the modified handler elsewhere? Use can-util/dom/data insetad?

2017-04-27 18:45 UTC, nlundquist commented on dom/events/delegate/derive-enter-leave.js
> +        return origHandler.call(this, event);
Should I create a PointerEvent or MouseEvent with the event type expected by the delegate handler? Currently this passes an event with the mapped type (ex. passes mouseover event for delegated mouseenter).

2017-04-27 18:48 UTC, nlundquist commented
After this is merged should can-event be modifed to include this? Or are we going to expect users to include this file if they want the functionality?

2017-04-27 19:26 UTC, matthewp commented
We talked about putting these types of things into their own packages and having users import them. cc @justinbmeyer

2017-04-27 19:32 UTC, justinbmeyer commented
@matthewp IMO, this shouldn't be in another package.  Making "standard" events bubble (like focus/blur) should probably be part of any core event-delegation library we provide.   If we make a `can-dom-event` or something that includes `addDelegateListener`, I'd expect this to be part of it.

2017-04-27 19:35 UTC, justinbmeyer requested changes

2017-04-27 19:35 UTC, justinbmeyer commented on dom/events/delegate/delegate-test.js
> +require('can-util/dom/events/delegate/derive-enter-leave');
why derive as the name?

2017-04-27 19:35 UTC, justinbmeyer commented on dom/events/delegate/derive-enter-leave.js
> +    this._derivedHandlers = this._derivedHandlers || {};
yeah, the element isn't a very good place.  I'd checkout the `singleReference` stuff.  You can put the delegating handler on `handler`

2017-04-27 19:35 UTC, justinbmeyer commented on dom/events/delegate/derive-enter-leave.js
> +    this._derivedHandlers[origHandler] = handler;
is this going to map to the same thing?  function.tostring()?

2017-04-27 21:30 UTC, nlundquist commented on dom/events/delegate/delegate-test.js
> +require('can-util/dom/events/delegate/derive-enter-leave');
this code derives enter and leave events from other events. i'm open to suggestions

2017-04-27 21:36 UTC, justinbmeyer commented
I think enter-leave is enough

Sent from my iPhone

> On Apr 27, 2017, at 4:30 PM, Nils Lundquist <notifications@github.com> wrote:
> 
> @nlundquist commented on this pull request.
> 
> In dom/events/delegate/delegate-test.js:
> 
> > @@ -5,6 +5,7 @@ var domEvents = require('can-util/dom/events/');
>  var domDispatch = require('can-util/dom/dispatch/');
>  var domData = require('can-util/dom/data/');
>  require('can-util/dom/events/delegate/');
> +require('can-util/dom/events/delegate/derive-enter-leave');
> this code derives enter and leave events from other events. i'm open to suggestions
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-04-27 23:20 UTC, justinbmeyer commented on dom/events/delegate/enter-leave.js
> +    handler = singleRef.getAndDelete(handler, cid(this)+eventType);
yay!

2017-04-27 23:21 UTC, justinbmeyer commented on dom/events/delegate/enter-leave.js
> +var domEvents = require("../events"),
make sure tabs, not spaces are used.  Also, if we did include some of jQuery's code here, make sure to add a comment referencing it and their copyright.

2017-04-27 23:21 UTC, justinbmeyer requested changes
add jQuery's copyright if we used some of their source.

2017-04-27 23:42 UTC, nlundquist commented on dom/events/delegate/enter-leave.js
> +var domEvents = require("../events"),
there's maybe one line that still resembles their code but I'll add the copyright just to be safe

2017-04-27 23:46 UTC, nlundquist commented
Only a line or two still resemble JQ but I've added the copyright just to be safe.

2017-04-28 22:03 UTC, nlundquist commented
@justinbmeyer once I have a final go ahead I'll merge this, make a minor version release and update can-event to use the new version and require 'enter-leave.js'

2017-05-01 16:30 UTC, merged