Fixes #265. Adds usage docs and require statements to some functions
canjs/can-util pull request #266
Opened 2017-05-04 22:30 UTC by mjstahl

2017-05-04 22:56 UTC, chasenlehara requested changes
Looks great! I left a couple comments on some things that could be improved throughout the files, but this looks good to merge after those are fixed.

2017-05-04 22:56 UTC, chasenlehara commented on dom/frag/frag.js
> +    var frag = require("can-util/dom/frag/");
We avoid the short (StealJS-friendly) path for users of other module loaders which don’t support this syntax.

2017-05-04 22:56 UTC, chasenlehara commented on js/string/string.js
> +	 * ```
I would explicitly mark any code blocks with ```js

2017-05-05 15:42 UTC, mjstahl commented on js/string/string.js
> +	 * ```
fixed.

2017-05-05 15:42 UTC, mjstahl commented on dom/frag/frag.js
> +    var frag = require("can-util/dom/frag/");
Updated this, and the other `require` lines

2017-05-05 16:25 UTC, chasenlehara approved these changes

2017-05-05 18:06 UTC, merged