Safe attributes
canjs/can-util pull request #282
Opened 2017-06-16 16:56 UTC by andrejewski

2017-06-16 17:20 UTC, phillipskevin requested changes
Just one small thing in a couple places. Otherwise, this looks great.

2017-06-16 17:20 UTC, phillipskevin commented on dom/events/attributes/attributes.js
> +	domData.set.call(target, "canAttributesObserver", observer);
should this be `attributesObserverKey`?

2017-06-16 17:20 UTC, phillipskevin commented on dom/events/attributes/attributes.js
> +	var observer = domData.get.call(target, "canAttributesObserver");
same thing... should this be `attributesObserverKey`?

2017-06-16 17:28 UTC, andrejewski commented
@phillipskevin Fixed based on your review, thanks

2017-06-16 17:28 UTC, phillipskevin approved these changes

2017-06-22 16:09 UTC, phillipskevin commented
going to close this one since #285 was merged instead.

2017-06-22 16:09 UTC, closed without merging